- name: Ensure Docker is installed
  apt:
    name: docker.io
    state: present
    update_cache: yes
  become: yes  # <== add only here

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Stop existing todo-app container
  shell: docker rm -f todo-app || true

- name: Run the todo-app container
  shell: docker run -d --name todo-app -p 8081:8080 todo-app

